export const SERVICE_CONFIG = {
  SERVICE_NAME: "auth",
  SERVICE_PORT: process.env.SERVICE_PORT ?? 3101,
  SERVICE_GRPC_PORT: process.env.SERVICE_GRPC_PORT ?? 31001,
  NODE_ENV: process.env.NODE_ENV ?? "development",
};

export const PG_CONFIG = {
  CONFIG_POSTGRESQL_USER_HOST: process.env.CONFIG_POSTGRESQL_USER_HOST,
  CONFIG_POSTGRESQL_USER_PORT: process.env.CONFIG_POSTGRESQL_USER_PORT,
  CONFIG_POSTGRESQL_USER_USERNAME: process.env.CONFIG_POSTGRESQL_USER_USERNAME,
  CONFIG_POSTGRESQL_USER_PASSWORD: process.env.CONFIG_POSTGRESQL_USER_PASSWORD,
  CONFIG_POSTGRESQL_USER_DBNAME: process.env.CONFIG_POSTGRESQL_USER_DBNAME,
};

export const REDIS_CONFIG = {
  CONFIG_REDIS_HOST: process.env.CONFIG_REDIS_HOST,
  CONFIG_REDIS_PORT: process.env.CONFIG_REDIS_PORT,
  CONFIG_REDIS_PASSWORD: process.env.CONFIG_REDIS_PASSWORD,
  CONFIG_REDIS_DBNAME: process.env.CONFIG_REDIS_DBNAME,
};

export const JWT_CONFIG = {
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN,
};
