// Error codes constants

export const ERROR_CODES = {
  // Authentication errors
  AUTH: {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    TOKEN_INVALID: "TOKEN_INVALID",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
  },

  // Validation errors
  VALIDATION: {
    REQUIRED_FIELD: "REQUIRED_FIELD",
    INVALID_FORMAT: "INVALID_FORMAT",
    INVALID_LENGTH: "INVALID_LENGTH",
    INVALID_EMAIL: "INVALID_EMAIL",
    INVALID_PASSWORD: "INVALID_PASSWORD",
  },

  // Resource errors
  RESOURCE: {
    NOT_FOUND: "RESOURCE_NOT_FOUND",
    ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
    CONFLICT: "RESOURCE_CONFLICT",
  },

  // System errors
  SYSTEM: {
    ERROR: "ERROR",
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    DATABASE_ERROR: "DATABASE_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
  },
} as const;
