// Error codes constants

export const SUCCESS_CODES = {
  // Authentication errors
  AUTH: {
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",
    VERIFY_EMAIL_SUCCESS: "VERIFY_EMAIL_SUCCESS",
    VERIFY_PHONE_SUCCESS: "VERIFY_PHONE_SUCCESS",
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    CHANGE_EMAIL_SUCCESS: "CHANGE_EMAIL_SUCCESS",
    CHANGE_PHONE_SUCCESS: "CHANGE_PHONE_SUCCESS",
    CHANGE_USERNAME_SUCCESS: "CHANGE_USERNAME_SUCCESS",
  },
  // System errors
  SYSTEM: {
    SUCCESS: "SUCCESS",
    CREATE_SUCCESS: "CREATE_SUCCESS",
    UPDATE_SUCCESS: "UPDATE_SUCCESS",
    DELETE_SUCCESS: "DELETE_SUCCESS",
  },
} as const;
