// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: src/protos/auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Metadata } from "@grpc/grpc-js";

export const protobufPackage = "com.wibu.auth";

/** The request message containing the token. */
export interface ValidateTokenRequest {
  token: string;
}

/** The response message containing user information or an error. */
export interface ValidateTokenResponse {
  userId: string;
  email: string;
  isValid: boolean;
  /** Empty if token is valid */
  error: string;
  roles: string[];
  permissions: string[];
  sessionId: string;
  deviceId: string;
}

function createBaseValidateTokenRequest(): ValidateTokenRequest {
  return { token: "" };
}

export const ValidateTokenRequest: MessageFns<ValidateTokenRequest> = {
  encode(
    message: ValidateTokenRequest,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number
  ): ValidateTokenRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateTokenRequest {
    return {
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: ValidateTokenRequest): unknown {
    const obj: any = {};
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateTokenRequest>, I>>(
    base?: I
  ): ValidateTokenRequest {
    return ValidateTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateTokenRequest>, I>>(
    object: I
  ): ValidateTokenRequest {
    const message = createBaseValidateTokenRequest();
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseValidateTokenResponse(): ValidateTokenResponse {
  return {
    userId: "",
    email: "",
    isValid: false,
    error: "",
    roles: [],
    permissions: [],
    sessionId: "",
    deviceId: "",
  };
}

export const ValidateTokenResponse: MessageFns<ValidateTokenResponse> = {
  encode(
    message: ValidateTokenResponse,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.isValid !== false) {
      writer.uint32(24).bool(message.isValid);
    }
    if (message.error !== "") {
      writer.uint32(34).string(message.error);
    }
    for (const v of message.roles) {
      writer.uint32(42).string(v!);
    }
    for (const v of message.permissions) {
      writer.uint32(50).string(v!);
    }
    if (message.sessionId !== "") {
      writer.uint32(58).string(message.sessionId);
    }
    if (message.deviceId !== "") {
      writer.uint32(66).string(message.deviceId);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number
  ): ValidateTokenResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateTokenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isValid = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.roles.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.permissions.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateTokenResponse {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      isValid: isSet(object.isValid)
        ? globalThis.Boolean(object.isValid)
        : false,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      roles: globalThis.Array.isArray(object?.roles)
        ? object.roles.map((e: any) => globalThis.String(e))
        : [],
      permissions: globalThis.Array.isArray(object?.permissions)
        ? object.permissions.map((e: any) => globalThis.String(e))
        : [],
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : "",
      deviceId: isSet(object.deviceId)
        ? globalThis.String(object.deviceId)
        : "",
    };
  },

  toJSON(message: ValidateTokenResponse): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.isValid !== false) {
      obj.isValid = message.isValid;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.roles?.length) {
      obj.roles = message.roles;
    }
    if (message.permissions?.length) {
      obj.permissions = message.permissions;
    }
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.deviceId !== "") {
      obj.deviceId = message.deviceId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateTokenResponse>, I>>(
    base?: I
  ): ValidateTokenResponse {
    return ValidateTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateTokenResponse>, I>>(
    object: I
  ): ValidateTokenResponse {
    const message = createBaseValidateTokenResponse();
    message.userId = object.userId ?? "";
    message.email = object.email ?? "";
    message.isValid = object.isValid ?? false;
    message.error = object.error ?? "";
    message.roles = object.roles?.map((e) => e) || [];
    message.permissions = object.permissions?.map((e) => e) || [];
    message.sessionId = object.sessionId ?? "";
    message.deviceId = object.deviceId ?? "";
    return message;
  },
};

/** The authentication service definition. */
export interface AuthService {
  /** Validates a token and returns user information */
  ValidateToken(
    request: ValidateTokenRequest,
    metadata?: Metadata
  ): Promise<ValidateTokenResponse>;
}

export const AuthServiceServiceName = "com.wibu.auth.AuthService";
export class AuthServiceClientImpl implements AuthService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || AuthServiceServiceName;
    this.rpc = rpc;
    this.ValidateToken = this.ValidateToken.bind(this);
  }
  ValidateToken(
    request: ValidateTokenRequest,
    metadata?: Metadata
  ): Promise<ValidateTokenResponse> {
    const data = ValidateTokenRequest.encode(request).finish();
    const promise = this.rpc.request(
      this.service,
      "ValidateToken",
      data,
      metadata
    );
    return promise.then((data) =>
      ValidateTokenResponse.decode(new BinaryReader(data))
    );
  }
}

interface Rpc {
  request(
    service: string,
    method: string,
    data: Uint8Array,
    metadata?: Metadata
  ): Promise<Uint8Array>;
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
