/**
 * Defines all available permissions in the system.
 * Each permission should be a string for easier management and potential future storage/comparison.
 */
export enum Permission {
  // Content
  CONTENT_VIEW = "CONTENT_VIEW",
  ANIME_CREATE = "ANIME_CREATE",
  MANGA_CREATE = "MANGA_CREATE",
  NOVEL_CREATE = "NOVEL_CREATE",
  ANIME_EDIT_OWN = "ANIME_EDIT_OWN",
  MANGA_EDIT_OWN = "MANGA_EDIT_OWN",
  NOVEL_EDIT_OWN = "NOVEL_EDIT_OWN",
  ANIME_EDIT_ALL = "ANIME_EDIT_ALL",
  MANGA_EDIT_ALL = "MANGA_EDIT_ALL",
  NOVEL_EDIT_ALL = "NOVEL_EDIT_ALL",
  ANIME_PUBLISH_IMMEDIATE = "ANIME_PUBLISH_IMMEDIATE",
  MANGA_PUBLISH_IMMEDIATE = "MANGA_PUBLISH_IMMEDIATE",
  NOVEL_PUBLISH_IMMEDIATE = "NOVEL_PUBLISH_IMMEDIATE",
  ANIME_SUBMIT_FOR_APPROVAL = "ANIME_SUBMIT_FOR_APPROVAL",
  MANGA_SUBMIT_FOR_APPROVAL = "MANGA_SUBMIT_FOR_APPROVAL",
  NOVEL_SUBMIT_FOR_APPROVAL = "NOVEL_SUBMIT_FOR_APPROVAL",
  ANIME_APPROVE = "ANIME_APPROVE",
  MANGA_APPROVE = "MANGA_APPROVE",
  NOVEL_APPROVE = "NOVEL_APPROVE",
  ANIME_TRANSLATE_RAW = "ANIME_TRANSLATE_RAW",
  MANGA_TRANSLATE_RAW = "MANGA_TRANSLATE_RAW",
  NOVEL_TRANSLATE_RAW = "NOVEL_TRANSLATE_RAW",

  // Comment
  COMMENT_VIEW = "COMMENT_VIEW",
  COMMENT_CREATE = "COMMENT_CREATE",
  COMMENT_EDIT_OWN = "COMMENT_EDIT_OWN",
  COMMENT_EDIT_ALL = "COMMENT_EDIT_ALL",
  COMMENT_DELETE_OWN = "COMMENT_DELETE_OWN",
  COMMENT_DELETE_ALL = "COMMENT_DELETE_ALL",

  // User & Group Management
  USER_VIEW = "USER_VIEW",
  USER_MANAGE = "USER_MANAGE",
  SUBADMIN_MANAGE = "SUBADMIN_MANAGE",
  GROUP_MANAGE = "GROUP_MANAGE",
  GROUP_MEMBER_MANAGE = "GROUP_MEMBER_MANAGE",

  // System
  SYSTEM_CONFIG = "SYSTEM_CONFIG",

  // E-commerce
  SELLER_MANAGE_PRODUCT = "SELLER_MANAGE_PRODUCT",
  SELLER_VIEW_ORDERS = "SELLER_VIEW_ORDERS",
  BUYER_MAKE_ORDER = "BUYER_MAKE_ORDER",
  BUYER_VIEW_OWN_ORDERS = "BUYER_VIEW_OWN_ORDERS",

  // Special permission for full access
  FULL_ACCESS = "FULL_ACCESS",
}
